# Generated by Django 4.2 on 2024-03-23 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('progress_status', models.CharField(choices=[('progress', 'Progress'), ('pending', 'Pending'), ('testing', 'Testing'), ('complete', 'Complete'), ('not_assigned', 'Not assigned'), ('awaiting', 'Awaiting')], default='progress', max_length=30)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='received_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('emoji', models.CharField(blank=True, max_length=1, null=True)),
                ('emotion_comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('pri_status', models.CharField(choices=[('medium', 'Medium'), ('low', 'Low'), ('high', 'High')], default='medium', max_length=30)),
                ('progress_status', models.CharField(choices=[('progress', 'Progress'), ('pending', 'Pending'), ('testing', 'Testing'), ('complete', 'Complete'), ('not_assigned', 'Not assigned'), ('awaiting', 'Awaiting')], default='progress', max_length=30)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='endpoints.project')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('green', 'Satisfaction'), ('blue', 'Calm/Relieved'), ('yellow', 'Mixed Feelings/Neutral'), ('red', 'Stressed/Frustrated')], default='green', max_length=30)),
                ('what_contributed_most', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('what_challenges_encounterd', models.TextField(blank=True, null=True)),
                ('took_more_or_less_time', models.TextField(blank=True, null=True)),
                ('What_did_you_learn', models.TextField(blank=True, null=True)),
                ('if_approach_task_again', models.TextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('reciepient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
