# Generated by Django 5.0.3 on 2024-04-02 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('green', 'Satisfaction'), ('red', 'Stressed/Frustrated'), ('yellow', 'Mixed Feelings/Neutral'), ('blue', 'Calm/Relieved')], max_length=10)),
                ('what_contributed_most', models.CharField(max_length=255)),
                ('challenges_encountered', models.TextField()),
                ('took_more_or_less_time', models.TextField()),
                ('what_did_you_learn', models.TextField()),
                ('approach_task_again', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='endpoints.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
