# Generated by Django 5.0.3 on 2024-04-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_taskreflection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreflection',
            name='mood',
            field=models.CharField(max_length=10),
        ),
    ]
