# Generated by Django 5.0.3 on 2024-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_alter_taskreflection_mood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
